name: Docker Image CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . -t homepage
          docker tag homepage ${{ secrets.DOCKER_USERNAME }}/homepage:ci-v$GITHUB_RUN_NUMBER
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/homepage
